ALTER TABLE kebaya_items ADD COLUMN categories TEXT NOT NULL DEFAULT '[]';
ALTER TABLE kebaya_items ADD COLUMN measurements TEXT NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY CHECK (id = 'main'),
  studio_name TEXT NOT NULL,
  tagline TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'maintenance', 'coming-soon')),
  location_label TEXT NOT NULL,
  whatsapp_number TEXT NOT NULL,
  email TEXT NOT NULL,
  address TEXT NOT NULL,
  instagram_url TEXT NOT NULL,
  tiktok_url TEXT NOT NULL,
  maps_url TEXT NOT NULL,
  currency TEXT NOT NULL CHECK (currency = 'IDR'),
  default_product_status TEXT NOT NULL CHECK (default_product_status IN ('available', 'rented', 'maintenance')),
  default_sort TEXT NOT NULL CHECK (default_sort IN ('newest', 'price-low', 'price-high', 'featured')),
  catalog_card_mode TEXT NOT NULL CHECK (catalog_card_mode IN ('minimal', 'standard', 'detailed')),
  show_prices INTEGER NOT NULL CHECK (show_prices IN (0, 1)),
  show_availability_badges INTEGER NOT NULL CHECK (show_availability_badges IN (0, 1)),
  show_product_code INTEGER NOT NULL CHECK (show_product_code IN (0, 1)),
  show_product_model INTEGER NOT NULL CHECK (show_product_model IN (0, 1)),
  show_product_size INTEGER NOT NULL CHECK (show_product_size IN (0, 1)),
  show_product_color INTEGER NOT NULL CHECK (show_product_color IN (0, 1)),
  show_product_description INTEGER NOT NULL CHECK (show_product_description IN (0, 1)),
  show_card_cta INTEGER NOT NULL CHECK (show_card_cta IN (0, 1)),
  default_mobile_grid INTEGER NOT NULL CHECK (default_mobile_grid IN (1, 2, 3)),
  default_desktop_grid INTEGER NOT NULL CHECK (default_desktop_grid IN (2, 3, 4)),
  brand_color TEXT NOT NULL,
  accent_color TEXT NOT NULL,
  background_color TEXT NOT NULL,
  text_color TEXT NOT NULL,
  primary_color TEXT NOT NULL,
  surface_color TEXT NOT NULL,
  border_color TEXT NOT NULL,
  border_radius INTEGER NOT NULL CHECK (border_radius >= 0 AND border_radius <= 32),
  logo_url TEXT NOT NULL,
  favicon_url TEXT NOT NULL,
  show_promo_banner INTEGER NOT NULL CHECK (show_promo_banner IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO site_settings (
  id,
  studio_name,
  tagline,
  status,
  location_label,
  whatsapp_number,
  email,
  address,
  instagram_url,
  tiktok_url,
  maps_url,
  currency,
  default_product_status,
  default_sort,
  catalog_card_mode,
  show_prices,
  show_availability_badges,
  show_product_code,
  show_product_model,
  show_product_size,
  show_product_color,
  show_product_description,
  show_card_cta,
  default_mobile_grid,
  default_desktop_grid,
  brand_color,
  accent_color,
  background_color,
  text_color,
  primary_color,
  surface_color,
  border_color,
  border_radius,
  logo_url,
  favicon_url,
  show_promo_banner,
  updated_at
)
VALUES (
  'main',
  'Farsha Studio',
  'Premium kebaya rental studio',
  'active',
  'Jakarta Barat, Indonesia',
  '+62 812-3456-7890',
  'hello@farshastudio.com',
  'Jl. Kebon Jeruk Raya No. 45, Jakarta Barat, DKI Jakarta 11530',
  'https://instagram.com/farshastudio',
  'https://tiktok.com/@farshastudio',
  'https://maps.google.com/?q=Farsha%20Studio%20Jakarta%20Barat',
  'IDR',
  'available',
  'newest',
  'standard',
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  3,
  '#111111',
  '#111111',
  '#FFFFFF',
  '#111111',
  '#111111',
  '#FFFFFF',
  '#E5E5E5',
  0,
  '',
  '',
  1,
  '2026-06-29T00:00:00.000Z'
)
ON CONFLICT(id) DO NOTHING;
